// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMyGN4FyQ1W60RxDPH7mVXm8tASmRGbdE',
    appId: '1:420410435196:web:cfbf25efd285457a804bf9',
    messagingSenderId: '420410435196',
    projectId: 'herodex-3000',
    authDomain: 'herodex-3000.firebaseapp.com',
    storageBucket: 'herodex-3000.firebasestorage.app',
    measurementId: 'G-NJMELEFZ98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGTrFmkUO4W_4wI3LxYa3r2pejMq-5XI',
    appId: '1:420410435196:android:acaa8de121a16619804bf9',
    messagingSenderId: '420410435196',
    projectId: 'herodex-3000',
    storageBucket: 'herodex-3000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZFDJOxmrMLeCAwTUpVYjTgIsfniCNbg',
    appId: '1:420410435196:ios:2398e3dfe49bef97804bf9',
    messagingSenderId: '420410435196',
    projectId: 'herodex-3000',
    storageBucket: 'herodex-3000.firebasestorage.app',
    iosBundleId: 'com.example.flutterHerodex3000',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZFDJOxmrMLeCAwTUpVYjTgIsfniCNbg',
    appId: '1:420410435196:ios:2398e3dfe49bef97804bf9',
    messagingSenderId: '420410435196',
    projectId: 'herodex-3000',
    storageBucket: 'herodex-3000.firebasestorage.app',
    iosBundleId: 'com.example.flutterHerodex3000',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMyGN4FyQ1W60RxDPH7mVXm8tASmRGbdE',
    appId: '1:420410435196:web:fa282cd3fb849a10804bf9',
    messagingSenderId: '420410435196',
    projectId: 'herodex-3000',
    authDomain: 'herodex-3000.firebaseapp.com',
    storageBucket: 'herodex-3000.firebasestorage.app',
    measurementId: 'G-E1GQLGG47J',
  );
}
